insert into beer (id, alcohol_content, category, ingredients, name, price) values (null, '4.5%', 'Premium Larger','Malte de Cevada, Água e Lúpulo', 'Heineken', 3) ;
insert into beer (id, alcohol_content, category, ingredients, name, price) values (null, '3.5%', 'Larger','Lúpulo, Cevada, Malte e Água', 'Bhrama Premium Puro Malte', 1.8) ;
insert into beer (id, alcohol_content, category, ingredients, name, price) values (null, '4.0%', 'Pilsen','Lúpulo, Cevada, Trigo e Água', 'Eisenbahn', 1.8) ;
insert into beer (id, alcohol_content, category, ingredients, name, price) values (null, '3.0%', 'Pilsen','Àgua, Cereais não maltados e Lúpulo', 'Skol', 1.25) ;
insert into beer (id, alcohol_content, category, ingredients, name, price) values (null, '3.2%', 'Pilsen','Àgua, Cereais não maltados e Lúpulo', 'Bhrama', 1.5) ;
insert into beer (id, alcohol_content, category, ingredients, name, price) values (null, '4%', 'Larger','Lúpulo, Cevada, Malte e Água', 'Bhrama Bock', 3.5) ;
insert into beer (id, alcohol_content, category, ingredients, name, price) values (null, '4.5%', 'Larger','Malte de Cevada, Água e Lúpulo', 'Imperio', 2) ;
insert into beer (id, alcohol_content, category, ingredients, name, price) values (null, '4.0%', 'Wiss','Lúpulo, Trigo e Água', 'Eisenbahn Wiss', 1.8) ;
insert into beer (id, alcohol_content, category, ingredients, name, price) values (null, '3.0%', 'Pilsen','Àgua, Cereais não maltados e Lúpulo', 'Skol Puro Malte', 1.25) ;
insert into beer (id, alcohol_content, category, ingredients, name, price) values (null, '3.2%', 'Wiss','Lúpulo, Trigo e Água', 'Baden Baden Wiss', 15.5) ;
insert into beer (id, alcohol_content, category, ingredients, name, price) values (null, '3.2%', 'Wiss','Lúpulo, Trigo e Água', 'Baden Baden Wiss Black', 20.5) ;
insert into beer (id, alcohol_content, category, ingredients, name, price) values (null, '3.2%', 'Black','Lúpulo, Cevada, Chocolate e Água', 'Baden Baden Chocolate', 18.5) ;
insert into beer (id, alcohol_content, category, ingredients, name, price) values (null, '3.2%', 'Black','Àgua, Cereais não maltados, Café e Lúpulo', 'Bhrama Back', 8.5) ;
insert into beer (id, alcohol_content, category, ingredients, name, price) values (null, '3.0%', 'Pilsen','Àgua, Cereais não maltados e Lúpulo', 'Itaipava', 1.0) ;
insert into beer (id, alcohol_content, category, ingredients, name, price) values (null, '3.0%', 'Pilsen','Àgua, Cereais não maltados e Lúpulo', 'Bavaria', 0.5) ;